engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "server/src/*.ts"
  - "server/src/**/*.ts"
  - "server/src/__tests__/*.spec.ts"
exclude_paths:
- node_modules/
- client/
- server/build/