language: node_js
node_js:
 - "stable"
script:
 - yarn test
services:
  -postgresql
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_success:
  - yarn run coveralls
  - yarn run coverage