language: node_js
node_js:
  - "node"

services:
  - postgresql

install:
- cd server
- yarn add -g typescript ts-node
- yarn -q --no-color --no-progress

before_script:
  - psql -c 'CREATE DATABASE travis_cospik;' -U postgres

script:
  - yarn test

after_success:
  - yarn run report-coverage
  - yarn run codeclimate-report