
// ADMIN ACTION CONSTANTS
export const ADMIN_SIGN_IN_REQUEST = "ADMIN_SIGN_IN_REQUEST";
export const ADMIN_SIGN_IN_SUCCESS = "ADMIN_SIGN_IN_SUCCESS";
export const ADMIN_SIGN_IN_FAILURE = "ADMIN_SIGN_IN_FAILURE";

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAILURE = "ADMIN_REGISTER_FAILURE";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

// NOTIFICATIONS
export const SET_NOTIFY = "SET_NOTIFY";
export const CLOSE_NOTIFY = "CLOSE_NOTIFY";
