
// ADMIN ACTION CONSTANTS
export const ADMIN_SIGN_IN_REQUEST = "ADMIN_SIGN_IN_REQUEST";
export const ADMIN_SIGN_IN_SUCCESS = "ADMIN_SIGN_IN_SUCCESS";
export const ADMIN_SIGN_IN_FAILURE = "ADMIN_SIGN_IN_FAILURE";

export const ADMIN_REGISTER_REQUEST = "ADMIN_REGISTER_REQUEST";
export const ADMIN_REGISTER_SUCCESS = "ADMIN_REGISTER_SUCCESS";
export const ADMIN_REGISTER_FAILURE = "ADMIN_REGISTER_FAILURE";
export const SET_ADMIN = "SET_ADMIN";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

// NOTIFICATIONS
export const SET_NOTIFY = "SET_NOTIFY";
export const CLOSE_NOTIFY = "CLOSE_NOTIFY";


// STUDENT CONSTANTS
export const GET_ALLSTUDENT_REQUEST = "GET_ALLSTUDENT_REQUEST";
export const GET_ALLSTUDENT_SUCCESS = "GET_ALLSTUDENT_SUCCESS";
export const GET_ALLSTUDENT_FAILURE = "GET_ALLSTUDENT_FAILURE";
